services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
    networks:
      - "mongo-network"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ifname: eth0
      MONGO_DB_URI: mongodb://root:root@mongo:27017
      APP_ENV: production
    container_name: firedns
    ulimits:
      memlock: -1
    command: ./main
    ports:
      - "2053:2053/udp"
    networks:
      - "mongo-network"


volumes:
  mongo-data:


networks:
  mongo-network: